Draft blog for conferences 2021
pharmaR/pharmaR.github.io pull request #58
Opened 2021-03-09 04:32 UTC by jmanitz

2021-03-10 16:24 UTC, andyofsmeg requested changes

2021-03-10 16:24 UTC, andyofsmeg commented on content/blog/2021-03-08-status-update-conferences-2021.Rmd
> +* Additional submissions are ongoing, so stay tuned for updates.
I suggest linking to the existing presentations page with something like this (with a relative link instead of the full one that I've written), 'All public presentations will be made available on the [presentations page](https://www.pharmar.org/present/) where you can also find historical presentations'

2021-03-11 15:18 UTC, marlycormar commented
Hi @jmanitz! Thank you for writing this blog post. I added some minor changes in a PR on your branch: https://github.com/jmanitz/pharmaR.github.io/pull/3.

2021-03-12 20:30 UTC, jmanitz commented on content/blog/2021-03-08-status-update-conferences-2021.Rmd
> +* Additional submissions are ongoing, so stay tuned for updates.
good idea

2021-03-15 10:26 UTC, andyofsmeg commented on content/blog/2021-03-08-status-update-conferences-2021.Rmd
> +* [Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2021/) (JSM; August 7-12, 2021): Topic-ontributed session accepted
'Contributed' missing the 'c' but I'll add this in a re-run.

2021-03-15 10:26 UTC, andyofsmeg approved these changes

2021-03-15 10:27 UTC, merged

2021-03-15 13:39 UTC, jmanitz commented on content/blog/2021-03-08-status-update-conferences-2021.Rmd
> +* [Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2021/) (JSM; August 7-12, 2021): Topic-ontributed session accepted
thank you