Getinvolved
pharmaR/pharmaR.github.io pull request #83
Opened 2022-09-29 10:13 UTC by andyofsmeg

New proposed page clarifying how people can get involved in our streams

2022-09-29 13:21 UTC, AARON-CLARK requested changes
Hi @andyofsmeg! Overall, it's a great addition. I have just a few comments / suggestions below.

2022-09-29 13:21 UTC, AARON-CLARK commented on content/contribute.md
> +For occasional news updates, you can join our [mailing list](https://lists.r-consortium.org/g/RConsortium-Validation-Hub). This will enable you and your colleagues to receive notifications of key upd
This may be outside the scope of this PR, but I just clicked on this [mailing list](https://lists.r-consortium.org/g/RConsortium-Validation-Hub) link and found the site to be pretty out of date & difficult to navigate. The executive committee member list is from 2019, and I found that most of the page has nothing to do with a mailing list at all. That is, I found it difficult to find where I could actually sign up for the mailing list. After a few minutes, I found a little button at the bottom of the page labeled `+ Join this group` but I'd argue I exerted way too much effort to achieve my goal (of signing up). A simple solution: create a new header titled "Join our mailing list" just before the sentence that reads: 

> "To manage your subscriptions to the public R Consortium mailing lists, please visit https://lists.r-consortium.org/g/Rconsortium-main/subgroups."

2022-09-29 13:21 UTC, AARON-CLARK commented on content/contribute.md
> +If you are willing and able to commit more time to the R Validation Hub then there are several options depending on your skills and interests.  If you do not feel you have the necessary technical ski
Consider inserting the word "mission" in to this sentence so it reads: "...commit more time to the R Validation Hub's **mission**, then there are several options..."

Consider adding a comma after the word "contribute"

2022-09-29 13:21 UTC, AARON-CLARK commented on content/contribute.md
> +The risk assessment shiny app is an extension of the {riskmetric} R package and provides a graphical interface to the {riskmetric} functionality.  It provides further exploratory capabilities in addi
Well said!

2022-09-29 13:21 UTC, AARON-CLARK commented on content/contribute.md
> +Shiny app development experience is highly desirable.
Consider amending to: "Shiny app development experience is highly desirable; specifically, experience with shiny modules and the {golem} package would be beneficial, but is not required."

2022-09-29 13:21 UTC, AARON-CLARK commented on content/contribute.md
> +The first milestone (projected three months) will be primarily focused around building an initial core team and more thoroughly scoping the project.
Three months from when? Maybe it'd be better to say: "(projected by Dec 2022)"?

2022-09-29 13:21 UTC, AARON-CLARK commented on content/contribute.md
> +If you have tried to implement any of the ideas the the R Validation Hub have outlined then we would love you to submit a case study to our [Case Study](https://github.com/pharmaR/case_studies) catal
Typo in first sentence: "the the"

Typo: capital S in: "USe our mailing list"

Without clicking on the case studies link, are you asking if people have used the RvalHub's **ideas** or one of their **tools**, like `{riskmetric}` and risk assessment? Or are you asking what methods their organizations use for assessing risk if **NOT** leveraging these RvalHub tools? It's unclear so I'm not how I can help... if I were a reader.

2022-09-30 15:03 UTC, andyofsmeg commented on content/contribute.md
> +For occasional news updates, you can join our [mailing list](https://lists.r-consortium.org/g/RConsortium-Validation-Hub). This will enable you and your colleagues to receive notifications of key upd
Good catch!  There's a limit to what you can do but I have tidied it a bit, removing a lot of the repeated detail from the website to reduce maintenance burden.  Realistically, people will generally only find the mailing list page by visiting the website.

2022-09-30 15:04 UTC, andyofsmeg commented on content/blog/2022-02-03-risk-assessment-app-update/index.md
>  The Risk Assessment App is an interactive web application serving as a front end application for the riskmetric R package. riskmetric is a framework to quantify risk by assessing a number of metrics
Point taken.  This is actually an old blog post that I happened to see when I was making another fix, but Marly was going by 'Gotti' at that point so I thought I would correct.  Otherwise I didn't review any of the rest.

2022-09-30 15:11 UTC, andyofsmeg commented on content/contribute.md
> +If you are willing and able to commit more time to the R Validation Hub then there are several options depending on your skills and interests.  If you do not feel you have the necessary technical ski
```suggestion
If you are willing and able to commit more time to the R Validation Hub's mission, then there are several options depending on your skills and interests.  If you do not feel you have the necessary technical skills to contribute then please don't let that stop you getting in touch and sharing ideas to support the implementation of a risk-based R package assessment.
```

2022-10-04 13:19 UTC, AARON-CLARK requested changes
Hi @andyofsmeg, I took another pass at it, adding suggestions where needed. Feel free to use as you see fit. Also, I thought it was just random at first, but it appears as though the first sentence of each paragraph has two spaces after each period. I started correcting them, but then noticed the pattern so I stopped. Was that intentional?

2022-10-04 13:19 UTC, AARON-CLARK commented on content/contribute.md
> +The {riskmetric} package collects metrics that support the idea of a risk-based evaluation of R packages.  The package collects and summarises various metrics and provides the means to quantify the r
```suggestion
The {riskmetric} package collects curated metrics that support the idea of a risk-based evaluation of R packages. The package not only collects and summarises these metrics, but also provides a means to quantify the risk via a weighted risk score.  {riskmetric} also serves as the backbone to the Risk Assessment shiny application.  For more information see the [package site](https://pharmar.github.io/riskmetric/) or [GitHub page](https://github.com/pharmaR/riskmetric).
```

2022-10-04 13:19 UTC, AARON-CLARK commented on content/contribute.md
> +The {riskmetric} team are currently looking to build features to support the idea of package cohorts.  We are also looking to refine some of the meta-information collected by riskmetric to better-ser
```suggestion
The {riskmetric} team are looking to build features to support the idea of package cohorts. Another priority is to refine some meta-information collected by {riskmetric} to better-serve the risk assessment application.  The development team also has a [backlog of other open issues](https://github.com/pharmaR/riskmetric/issues), including additional metrics that they would like to explore.
```

2022-10-04 13:19 UTC, AARON-CLARK commented on content/contribute.md
> +A fundamental understanding of R packages is essential for anyone looking to support the {riskmetric} team.  Package development experience is also highly beneficial.
```suggestion
A fundamental understanding of R packages is essential for anyone looking to support the {riskmetric} team. Package development experience is also highly beneficial.  
```

2022-10-04 13:19 UTC, AARON-CLARK commented on content/contribute.md
> +The risk assessment shiny app is an extension of the {riskmetric} R package and provides a graphical interface to the {riskmetric} functionality.  It provides further exploratory capabilities in addi
```suggestion
The risk assessment shiny app is an extension of the {riskmetric} R package, providing a graphical interface to the {riskmetric} functionality and a means to collaborate when assessing packages risk within an organization. It provides further exploratory capabilities in addition to the numeric metrics and improves ease-of-use for non-technical users. For more information see the [package GitHub page](https://github.com/pharmaR/risk_assessment).
```

2022-10-04 13:19 UTC, AARON-CLARK commented on content/contribute.md
> +If you have tried to implement any of the R Validation Hub's ideas, or used any of our tools, or even if you've decided to go own way, then we would love you to submit a case study describing what yo
```suggestion
If you have tried to implement any of the R Validation Hub's ideas, used our tools, or even if you've designed your own, we would love for you to submit a case study describing your actions to implement a GxP-compliant R environment to our [Case Study](https://github.com/pharmaR/case_studies) catalogue on GitHub.  Use our mailing list or GitHub issues to let us know of your intentions and we'll work with you to upload your written case study.  We're also pleased to share case studies verbally with the wider community.  You can find videos of previous presentations on our [case studies](/casestudies/) page.
```

2022-10-05 08:51 UTC, andyofsmeg commented
FYI I'm going to merge into the preview branch for others to see, then create a PR into the master branch.

2022-10-05 08:51 UTC, merged