Adding blog post and contributor updates
pharmaR/pharmaR.github.io pull request #95
Opened 2023-07-04 21:19 UTC by dgkf

* Adding a blog post for changes in participants, announcing new workstreams
* Updated `/contribute` page to include communications workstream and leadership sponsor roles

2023-08-08 21:12 UTC, dgkf commented
@jmanitz - Finally figured out why my blog post wasn't getting updated :facepalm: Let me know what you think. Feel free to merge if you approve, or request changes if you spot anything I missed.

2023-08-21 16:01 UTC, AARON-CLARK commented on content/contribute.md
> +### The [Risk Assessment Application](https://github.com/pharmaR/risk_assessment)
we changed our repo name to `riskassessment` a couple months ago to align with the naming convention set by `riskmetric`, so any instance pointing to the old `risk_assessment` repo or spelling, should be removed it possible.
```suggestion
### The [Risk Assessment Application](https://github.com/pharmaR/riskassessment)
```

2023-08-21 16:04 UTC, AARON-CLARK commented on content/contribute.md
> +ease-of-use for non-technical users. For more information see the [package
I just wanted to generalize this a little bit and mention how it's a great org level tool.
```suggestion
ease-of-use for organizations to adopt a risk-based approach to R package validation. For more information see the [package
```

2023-08-24 16:38 UTC, dgkf commented on content/contribute.md
> +looking for two new contributors, preferrably with an enthusiasm for social
Good call - this is out of date. I think we have good coverage in this group for now.

2023-08-24 19:57 UTC, dgkf commented on content/contribute.md
> +looking for two new contributors, preferrably with an enthusiasm for social
Removed this, as well as the Leadership Sponsors role, which has been supplanted by quarterly meetings with the R Consortium Pharma Oversight Committee

2023-08-29 13:52 UTC, AARON-CLARK requested changes
Hi @dgkf,

Sorry I somehow missed this review request. Good fixes on the `contribute/` page. I have just a couple comments on whether those `contribute/` changes should also carry through to the blog.

2023-08-29 13:52 UTC, AARON-CLARK commented on content/blog/2023-08-08-status-update.Rmd
> +plans for a website overhaul and to streamline our presentations.
Even though this blog post was dated for 8/8, I think it makes sense to update this section to use past tense given the recently filled positions.

```suggestion
### Communications Workstream

We opened & filled two positions for a new communications workstream. This role will 
focus on building connections across the R world, specifically our neighboring initiatives: 
the R Consortium, PhUSE, PSI AIMS, the R Submissions Working Group and ROpenSci. 
For the media-junkies, we have grand plans for a website overhaul and to streamline our 
presentations.
```

2023-08-29 13:52 UTC, AARON-CLARK commented on content/blog/2023-08-08-status-update.Rmd
> +contributor-focused priorities.
Is this reference to "senior leaders" still accurate? This is now the pharma oversight committee, correct? I know you got rid of the "senior leaders" section in `contribute/` so I'm not sure if this paragraph needs amending. It may be fine as is?

2023-09-05 19:27 UTC, dgkf commented on content/blog/2023-08-08-status-update.Rmd
> +contributor-focused priorities.
Thanks for spotting that! I updated it to reflect the cooperation with the R Consortium pharma oversight committee instead.

2023-09-05 19:37 UTC, AARON-CLARK approved these changes
👍🏼 I know you didn't re-request my review but it looks good to me. I'll approve but I'll let you merge.

2023-09-06 14:52 UTC, merged